### ISSUE TITLE
Could you share your hyper-parameter settings on three datasets?

### ISSUE THREAD

**Issue by LUUUUUUZ** [0215Arthur/HG-GNN#9]
I just run the `python main.py` with:

```
Epoch [1/20]                                                                       [115/1668]
Traceback (most recent call last):                                                           
  File "/data/lumy/workspace/SBRS/HG-GNN/main.py", line 246, in <module>                     
    train(conf, model, device, train_iter, test_iter)                                        
  File "/data/lumy/workspace/SBRS/HG-GNN/main.py", line 93, in train                         
    outputs = model(uid.to(device),                                                          
  File "/home/lumy/anaconda3/envs/HG-GNN/lib/python3.9/site-packages/torch/nn/modules/module.
py", line 889, in _call_impl                                                                 
    result = self.forward(*input, **kwargs)                                                  
  File "/data/lumy/workspace/SBRS/HG-GNN/models/HG_GNN.py", line 200, in forward             
    sess_user = self.sess_user_vector(user_embeds, node_embeds, mask)                        
  File "/data/lumy/workspace/SBRS/HG-GNN/models/HG_GNN.py", line 118, in sess_user_vector    
    hs = user_vec.unsqueeze(-2).repeat(1, mask.shape[1], 1)                                  
RuntimeError: Number of dimensions of repeat dims can not be smaller than number of dimension
s of tensor
[HGGNN] 0:[tmux]*M                                                     "root" 16:18 16-Jan-23
```

I checked line 118 in HG_GNN.py:
`hs = user_vec.unsqueeze(-2).repeat(1, mask.shape[1], 1)`
with:
user_vec.shape: [512,1,128]

I will appreciate If you could help me!
Thanks!

**Comment by WillyPKU** [comment]
I met the same problem as you. Have you solved it?
